### ISSUE TITLE
Reduce layers on RabbitMQ

### ISSUE THREAD

**Issue by brianharwell** [micdenny/docker-samples#1]
First off, thanks so much for creating this image! 

I reviewed your Dockerfile and I thought you did a bang up job in creating this image but I was curious why you have so many independent RUN statements. From the best practices documentation it suggests combining multiple statements into a single RUN statement to reduce unnecessary layers and reduce container size. I was curious if this was inadvertent, intentional for readability, or intentional due to the steps required to install Erlang and RabbitMQ.

I would appreciate your insight!

Thanks!

**Comment by micdenny** [comment]
Hi @brianharwell, yes you're right, the best practice is to combine multiple statement into a single RUN.

I don't remember where I took inspiration, but I think I looked at the [linux one](https://github.com/docker-library/rabbitmq/blob/master/3.6/alpine/Dockerfile) and probably an older version where there were a lot of RUN, as you see there still quite a lot of RUN in the official rabbitmq dockerfile, and probably there are reason for that.

Told this, looking again at my dockerfile it seems that all those command can be combined without problem

Would you mind to do the changes, and push a PR? 😄 if you want you can push the fix for the 3.6.9 version, and then create also the dockerfile for the newest version 3.6.12

**Comment by brianharwell** [comment]
Sure thing

**Comment by micdenny** [comment]
If we made good stuff, I can remove the `sample` label from the git repo 😄
